version: '3.5'

services:
  dcsa-template:
    container_name: dcsa_rmo
    build:
      .
    ports:
      - 9090:9090
    environment:
      - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-nosecurity}"
      - "ROOT_LOG_LEVEL=${ROOT_LOG_LEVEL:-INFO}"
      - "DCSA_LOG_LEVEL=${DCSA_LOG_LEVEL:-INFO}"
    logging:
      options:
        max-file: '10'
        max-size: 200k
    
