dcsa:
  specification:
    version: 3.0.0

spring:
  application:
    name: dcsa-rmo
    context-path: /rmo/v3
  profiles:
    active: nosecurity
    group:
      dev: nosecurity
      test: nosecurity
      prod: default

server:
  port: 9090
  error:
    include-binding-errors: on_param
    include-message: always

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    diskspace:
      enabled: false

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    org:
      springframework: ${SPRING_LOG_LEVEL:INFO}
      dcsa: ${DCSA_LOG_LEVEL:INFO}

---
# A profile for disabling security
spring:
  config:
    activate:
      on-profile: nosecurity

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
